# Generated by Django 6.0.3 on 2026-05-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecashApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcashmodel',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='expensemodel',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='addcashmodel',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
