# Generated by Django 6.0.3 on 2026-05-01 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecashApp', '0002_rename_datetime_addcashmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcashmodel',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addcashmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
